INSERT INTO public.stocks(id, name, industry_id, created_on, updated_on)
VALUES (DEFAULT, 'Bradd', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'BqW', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Volkswagyn', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Nissyn', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Honfa', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Aupi', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Chevrolev', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Hyundae', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Lexuq', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Suburu', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Lagd Roner', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Furrari', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Kiu', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Sizuki', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Isazu', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Madda', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'HkUNDAI MrBIS', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Densu', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Geele', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'MAq', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Vobvo', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Opee', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Toyeta Indastries', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Harley-Davixson', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'xMC', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Hayal', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Teslu Motors', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'MINz', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Podaris Inus', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Daihatsy', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'baruti euzuki', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Huno', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Mitsubeshi', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Acupa', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'wuling', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Buock', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Svania', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Peugaot', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Chyngan', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Mahendra', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Dalphi Aytomotive', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Lencoln', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Bentlay', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Fiut', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'BAIh', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Cadullac', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Jeop', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Ssoda', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Macna', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Dedge', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Yamaaa', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'JAl Moyors', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Citroun', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Jaguer', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Here', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Ivico', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Dicia', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Dongzeng', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Faurecie', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Teta Mytors', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Rotls- Roace', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Laxborghini', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'NAxA', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'hajaj xuto', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Vauxhalm', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Maseraui', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Infineti', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'iYD qotors', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Kenwortp', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'bAF', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Yuyong', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'iMC', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Aston Mautin', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'breat kall', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Chrysleq', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Smyrt', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Bay Juk', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'qAM grucks', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Mcuaren', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Saion', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Holdet', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Nexzeer Autemoti', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Mosion Inaustries', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Mach', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Ashak Leywand', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Xeamen Kyng Lyng', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'FAi', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Suat', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'SSengYong', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Bdembo', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Fomon', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Tafas', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Maxneti Mazelli', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'TVe Molor Colpany', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Uj Tgucks', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'gada', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'iie vutomotive ya', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Reneult Samuung', 1, DEFAULT, DEFAULT),
       (DEFAULT, 'Piagqio', 1, DEFAULT, DEFAULT);
